version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wishlist-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: wishlist-db
